### ISSUE TITLE
quit after window closed

### ISSUE THREAD

**Issue by Jun0413** [Lancerchiang/TouchBarGopher#1]
Below function can be overrode in `AppDelegate.swift`:
```swift
func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
    return true
}
```

**Comment by alxiong** [comment]
@Jun0413 Thanks for the suggestion! 
@Lancerchiang Please regenerate the executable and update the download link. Thanks!
